# Generated by Django 5.0.4 on 2024-04-12 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tasks_delete_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
    ]
